### ISSUE TITLE
ayuda

### ISSUE THREAD

**Issue by anderson-renteria** [hopechan/sisPrestamo3#3]
amigo e descargado su pagina, pero tengo un  problema en el momento de hacer el pago, "Fatal error: Interface 'Mike42\Escpos\PrintConnectors\PrintConnector' not found in D:\xampp\xxxx\xxx\xxx\sisPrestamo3-master-ori\vendor\mike42\escpos-php\src\Mike42\Escpos\PrintConnectors\CupsPrintConnector.php on line 23"... que puede ser ese problema gracias.

**Comment by hopechan** [comment]
Hola, esto se debe porque el sistema imprime un recibo utilizando una impresora térmica, pero puedes desabilitar esta funcionalidad comentando esta linea en el archivo _guardarPago.php_
![image](https://user-images.githubusercontent.com/7852335/70383984-02450a80-193d-11ea-8b3b-ec9907ebab2f.png)

**Comment by anderson-renteria** [comment]
excelente mi amigo gracias te califico con un 10.... (Y)  .... !!!!
